# shellcheck shell=bash
# DNS resolver profile optimization workflows.

dns_write_static_resolv_conf() {
    local v4_servers="$1"
    local v6_servers="$2"
    local server

    if [[ -L /etc/resolv.conf ]]; then
        quarantine_path /etc/resolv.conf "/etc/vps-optimize/quarantine/dns" >/dev/null 2>&1 || return 1
    fi

    {
        echo "# Generated by VPS-Optimize DNS optimization"
        echo "# Updated: $(date -Is 2>/dev/null || date)"
        for server in $v4_servers; do
            echo "nameserver $server"
        done
        for server in $v6_servers; do
            echo "nameserver $server"
        done
        echo "options timeout:2 attempts:3 rotate"
    } > /etc/resolv.conf
}

dns_disable_tailscale_dns() {
    local resolv_conf="${1:-/etc/resolv.conf}"

    command -v tailscale >/dev/null 2>&1 || return 0

    if tailscale set --accept-dns=false >/dev/null 2>&1; then
        echo -e "$(localized_text "${CYAN}已关闭 Tailscale DNS 接管，继续应用系统 DNS。${PLAIN}" "${CYAN}Tailscale DNS management is disabled. Continuing with system DNS changes.${PLAIN}" "${CYAN}Управление DNS через Tailscale отключено. Продолжается применение системного DNS.${PLAIN}")"
        return 0
    fi

    if grep -Eq '^[[:space:]]*nameserver[[:space:]]+(100\.100\.100\.100|fd7a:115c:a1e0::53)' "$resolv_conf" 2>/dev/null || \
       tailscale status --json 2>/dev/null | grep -Eq '"BackendState"[[:space:]]*:[[:space:]]*"Running"'; then
        echo -e "$(localized_text "${YELLOW}⚠️ Tailscale DNS 接管未关闭，仍会继续写入系统 DNS；如被再次覆盖，请恢复网络后执行 tailscale set --accept-dns=false。${PLAIN}" "${YELLOW}⚠️ Tailscale DNS management could not be disabled. System DNS will still be written; if it is overwritten again, run tailscale set --accept-dns=false after network recovery.${PLAIN}" "${YELLOW}⚠️ Не удалось отключить управление DNS через Tailscale. Системный DNS всё равно будет записан; если он снова будет перезаписан, после восстановления сети выполните tailscale set --accept-dns=false.${PLAIN}")"
    fi

    return 0
}

dns_apply_profile() {
    local profile_name="$1"
    local v4_servers="$2"
    local v6_servers="$3"
    local backup_dir all_servers resolved_active resolv_target

    confirm_risk_action "$(localized_text "更改系统 DNS 为 ${profile_name}" "Change system DNS to ${profile_name}" "Измените систему DNS на ${profile_name}.")" \
        "$(localized_text "/etc/resolv.conf 和 systemd-resolved DNS 配置" "/etc/resolv.conf and systemd-resolved DNS configurations" "Конфигурации /etc/resolv.conf и systemd с разрешением DNS")" \
        "$(localized_text "进入本菜单选择 [5] 恢复最近一次 DNS 备份，或手动恢复 ${DNS_OPTIMIZE_BACKUP_DIR}" "Enter this menu and select [5] to restore the latest DNS backup, or manually restore ${DNS_OPTIMIZE_BACKUP_DIR}" "Войдите в это меню и выберите [5], чтобы восстановить последнюю резервную копию DNS или вручную восстановить ${DNS_OPTIMIZE_BACKUP_DIR}.")" \
        "$(localized_text "DNS 写错会导致域名解析失败；当前 SSH 连接通常不会立即断开。" "Wrong writing of DNS will cause domain resolution to fail; the current SSH connection is usually not disconnected immediately." "Неправильная запись DNS приведет к сбою разрешения доменного имени; текущее соединение SSH обычно не разрывается сразу.")" || return 1

    dns_disable_tailscale_dns
    backup_dir=$(dns_backup_current_config)
    all_servers="${v4_servers} ${v6_servers}"

    resolved_active=0
    if command -v systemctl >/dev/null 2>&1 && systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        resolved_active=1
    fi

    if [[ "$resolved_active" -eq 1 ]]; then
        mkdir -p /etc/systemd/resolved.conf.d
        {
            echo "[Resolve]"
            echo "DNS=${all_servers}"
            echo "FallbackDNS="
        } > "$DNS_OPTIMIZE_RESOLVED_DROPIN"
        systemctl restart systemd-resolved >/dev/null 2>&1 || echo -e "$(localized_text "${YELLOW}⚠️ systemd-resolved 重启失败，已继续写入静态 resolv.conf。${PLAIN}" "${YELLOW}⚠️ systemd-resolved Restart failed and static resolv.conf has been written.${PLAIN}" "${YELLOW}⚠️ systemd решено. Не удалось перезапустить, и был записан статический файл resolv.conf.${PLAIN}")"

        resolv_target=$(readlink -f /etc/resolv.conf 2>/dev/null || true)
        if [[ "$resolv_target" != /run/systemd/resolve/* ]]; then
            dns_write_static_resolv_conf "$v4_servers" "$v6_servers" || return 1
        fi
    else
        dns_write_static_resolv_conf "$v4_servers" "$v6_servers" || return 1
    fi

    echo -e "$(localized_text "${GREEN}✅ DNS 已切换为 ${profile_name}${PLAIN}" "${GREEN}✅ DNS has been switched to ${profile_name}${PLAIN}" "${GREEN}✅ DNS заменен на ${profile_name}.${PLAIN}")"
    echo -e "IPv4 DNS: ${CYAN}${v4_servers}${PLAIN}"
    echo -e "IPv6 DNS: ${CYAN}${v6_servers}${PLAIN}"
    echo -e "$(localized_text "${YELLOW}已备份旧配置：${backup_dir}${PLAIN}" "${YELLOW}Has backed up the old configuration: ${backup_dir}${PLAIN}" "${YELLOW}создал резервную копию старой конфигурации: ${backup_dir}.${PLAIN}")"

    if getent hosts raw.githubusercontent.com >/dev/null 2>&1; then
        echo -e "$(localized_text "${GREEN}✅ DNS 解析测试通过。${PLAIN}" "${GREEN}✅ DNS analysis test passed.${PLAIN}" "${GREEN}✅ Анализ DNS пройден.${PLAIN}")"
    else
        echo -e "$(localized_text "${YELLOW}⚠️ DNS 已写入，但解析测试暂未通过；请检查网络、IPv6 可用性或 DNS 服务器连通性。${PLAIN}" "${YELLOW}⚠️ DNS was written, but the resolution test did not pass; check the network, IPv6 availability, or DNS server connectivity.${PLAIN}" "${YELLOW}⚠️ DNS записан, но проверка разрешения пока не пройдена; проверьте сеть, доступность IPv6 или подключение к DNS-серверу.${PLAIN}")"
    fi
}


func_dns_optimize() {
    while true; do
        clear
        echo -e "${CYAN}================================================${PLAIN}"
        print_breadcrumb "$(localized_text "网络/内核优化 > DNS 设置" "Network/Kernel Optimization > DNS settings" "Оптимизация сети/ядра > Настройка DNS")"
        echo -e "$(localized_text "${BOLD}DNS 设置${PLAIN}" "${BOLD}DNS settings${PLAIN}" "${BOLD}Настройка DNS${PLAIN}")"
        echo -e "${CYAN}================================================${PLAIN}"
        echo -e "$(localized_text "${YELLOW}可选择国内、国际或自定义 IPv4 / IPv6 DNS；检测到 Tailscale 时会先关闭其 DNS 接管。${PLAIN}" "${YELLOW}Choose China, international, or custom IPv4 / IPv6 DNS. Tailscale DNS management is disabled first when detected.${PLAIN}" "${YELLOW}Выберите DNS для Китая, международные или свои IPv4 / IPv6. При обнаружении Tailscale его управление DNS сначала отключается.${PLAIN}")"
        echo -e "------------------------------------------------"
        echo -e "$(localized_text "${GREEN}  1. 使用国内 DNS${PLAIN} ${YELLOW}(阿里 DNS + DNSPod)${PLAIN}" "${GREEN}  1. Use China DNS${PLAIN} ${YELLOW}(Alibaba DNS + DNSPod)${PLAIN}" "${GREEN}  1. Использовать DNS для Китая${PLAIN} ${YELLOW}(Alibaba DNS + DNSPod)${PLAIN}")"
        echo -e "$(localized_text "${GREEN}  2. 使用国际 DNS${PLAIN} ${YELLOW}(Cloudflare + Google)${PLAIN}" "${GREEN}  2. Use international DNS${PLAIN} ${YELLOW}(Cloudflare + Google)${PLAIN}" "${GREEN}  2. Использовать международные DNS${PLAIN} ${YELLOW}(Cloudflare + Google)${PLAIN}")"
        echo -e "$(localized_text "${GREEN}  3. 自定义 DNS${PLAIN} ${YELLOW}(分别填写 IPv4 / IPv6)${PLAIN}" "${GREEN}  3. Set custom DNS${PLAIN} ${YELLOW}(separate IPv4 / IPv6 values)${PLAIN}" "${GREEN}  3. Настроить свои DNS${PLAIN} ${YELLOW}(отдельно IPv4 / IPv6)${PLAIN}")"
        echo -e "$(localized_text "${GREEN}  4. 查看当前 DNS${PLAIN}" "${GREEN}  4. View current DNS${PLAIN}" "${GREEN}  4. Показать текущие DNS${PLAIN}")"
        echo -e "$(localized_text "${GREEN}  5. 恢复最近一次 DNS 备份${PLAIN}" "${GREEN}  5. Restore the latest DNS backup${PLAIN}" "${GREEN}  5. Восстановить последнюю копию DNS${PLAIN}")"
        echo -e "------------------------------------------------"
        echo -e "$(localized_text "${BLUE}  0. 返回上一级菜单 / q 返回${PLAIN}" "${BLUE}0. Back / q Back${PLAIN}" "${BLUE}0. Назад / q Назад${PLAIN}")"
        echo -e "${CYAN}================================================${PLAIN}"

        local choice v4_servers v6_servers raw_v4 raw_v6
        read_trimmed choice "$(localized_text "选择操作: " "Select an option: " "Выберите действие: ")"
        case "$choice" in
            1)
                dns_apply_profile "$(localized_text "国内 DNS" "Domestic DNS" "Внутренний DNS")" "223.5.5.5 119.29.29.29" "2400:3200::1 2402:4e00::"
                pause_return
                ;;
            2)
                dns_apply_profile "$(localized_text "国外 DNS" "Foreign DNS" "Иностранный DNS")" "1.1.1.1 8.8.8.8" "2606:4700:4700::1111 2001:4860:4860::8888"
                pause_return
                ;;
            3)
                read_trimmed raw_v4 "$(localized_text "请输入 IPv4 DNS（用逗号或空格分隔）: " "Please enter IPv4 DNS (separated by commas or spaces):" "Введите IPv4 DNS (через запятую или пробел):")"
                read_trimmed raw_v6 "$(localized_text "请输入 IPv6 DNS（用逗号或空格分隔）: " "Please enter IPv6 DNS (separated by commas or spaces):" "Введите IPv6 DNS (через запятую или пробел):")"
                v4_servers=$(dns_normalize_servers 4 "$raw_v4") || {
                    echo -e "$(localized_text "${RED}❌ IPv4 DNS 格式无效。${PLAIN}" "${RED}❌ IPv4 DNS The format is invalid.${PLAIN}" "${RED}❌ IPv4 DNS Неверный формат.${PLAIN}")"
                    pause_return
                    continue
                }
                v6_servers=$(dns_normalize_servers 6 "$raw_v6") || {
                    echo -e "$(localized_text "${RED}❌ IPv6 DNS 格式无效。${PLAIN}" "${RED}❌ IPv6 DNS The format is invalid.${PLAIN}" "${RED}❌ IPv6 DNS Неверный формат.${PLAIN}")"
                    pause_return
                    continue
                }
                dns_apply_profile "$(localized_text "自定义 DNS" "Custom DNS" "Пользовательский DNS")" "$v4_servers" "$v6_servers"
                pause_return
                ;;
            4)
                echo -e "${CYAN}--- /etc/resolv.conf ---${PLAIN}"
                sed -n '1,80p' /etc/resolv.conf 2>/dev/null || true
                if command -v resolvectl >/dev/null 2>&1; then
                    echo -e "\n${CYAN}--- resolvectl dns ---${PLAIN}"
                    resolvectl dns 2>/dev/null || true
                fi
                pause_return
                ;;
            5) dns_disable_tailscale_dns; dns_restore_latest_backup; pause_return ;;
            0|q|Q) break ;;
            *) echo -e "$(localized_text "${RED}❌ 无效选择！${PLAIN}" "${RED}❌ Invalid selection!${PLAIN}" "${RED}❌ Неверный выбор!${PLAIN}")"; sleep 1 ;;
        esac
    done
}

# ---------------------------------------------------------
# 23. 流量达量关机保护
# ---------------------------------------------------------
